### ISSUE TITLE
Latest Version stops to copy the BMPs

### ISSUE THREAD

**Issue by Blueforcer** [darkspr1te/MKSTFT_Marlin_Touch#13] opened 2020-03-04 22:46 UTC
I tried your latest Version. Unfortunately it stops in the middle of copying the pictures. No matter how many pictures I want to copy. Maybe there are also problems if he wants to alden the actual system. Unfortunately there are no error messages etc

I use the MKSTFT28. 

The last version ran fine. 

Do you have Dicord or something like that, to have a deeper look at it? Im also implementing new functions right now. maybe we can work together
Mine is Blueforcer#9801

**Comment by darkspr1te** [comment] 2020-03-05 06:27
Did you close because the issue is resolved ? if not try the TFT28 folder from the alternate icon folder, format sdcard fresh prior to use, do you get different results from this repo https://github.com/darkspr1te/BIGTREETECH-TouchScreenFirmware

**Comment by Blueforcer** [comment] 2020-03-05 07:55
Since its not an original MKS Display, i had to uncomment this line.
https://github.com/darkspr1te/MKSTFT_Marlin_Touch/blob/master/TFT/src/User/main.c#L34
Took me few hours to get it, but now its working xD

Now i had another little question:
ive implemented a new Gcode (M600) in the interfaceCmd.c. 
But although the command works, the display shows me "Unknown Command", after I confirmed it my new menu opens. How can I prevent this error message?

**Comment by darkspr1te** [comment] 2020-03-09 18:26
am currently adding in support for M600, the unknown comes from no correct ACK , i've not quite figured that part out yet.
the issue at line #34 (sd_deInit) results from the EEPROM side being shut down, as the next command expects to read to eeprom but the SPI has been shut down. Other boards support EEPROM on spi 2, this board uses SPI1 for SD+eeprom only different on chipselect (hence the added #define W25Qxx_CS     PB9 in variant.h)

**Comment by darkspr1te** [comment] 2020-03-20 06:05
fixed in commit [https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/commit/88121407d7b82c217321796031d049f0a63c299e](url)

**Closed as completed** 2020-03-20 06:06 UTC
